// 2026秋招公司数据 — 由cron自动更新
// 最后更新: 2026-05-30
window.CAMPUS_DATA = [
  {name:"字节跳动", industry:"互联网", tags:["研发+23%","5000+Offer"], url:"https://jobs.bytedance.com/campus", desc:"8月4日开启，研发岗需求暴增", deadline:"2026-09-15", source:"官网", referral:""},
  {name:"阿里巴巴", industry:"互联网", tags:["7000+Offer","AI岗>60%"], url:"https://campus.alibaba.com", desc:"8月5日启动，15个业务集团齐招", deadline:"2026-09-20", source:"官网", referral:""},
  {name:"腾讯", industry:"互联网", tags:["技术+产品"], url:"https://join.qq.com/", desc:"常规校招+阅文集团同步", deadline:"2026-09-25", source:"官网", referral:""},
  {name:"京东", industry:"互联网+零售", tags:["3.5万岗位","零售/科技"], url:"https://campus.jd.com/", desc:"7月28日启动，岗位量大管饱", deadline:"2026-08-30", source:"官网", referral:""},
  {name:"美团", industry:"互联网", tags:["6000人","技术>1/3"], url:"https://hr.meituan.com/web/campus", desc:"技术+运营双线招聘", deadline:"2026-09-15", source:"官网", referral:""},
  {name:"百度", industry:"互联网", tags:["提前批7.20","AI优先"], url:"https://talent.baidu.com/", desc:"提前批7月20日开启", deadline:"2026-08-15", source:"官网", referral:""},
  {name:"小红书", industry:"互联网", tags:["北上广深杭"], url:"https://job.xiaohongshu.com/campus", desc:"内容社区增长期", deadline:"2026-09-30", source:"官网", referral:""},
  {name:"快手", industry:"互联网", tags:["北京为主"], url:"https://campus.kuaishou.cn/", desc:"短视频赛道持续扩招", deadline:"2026-09-30", source:"官网", referral:""},
  {name:"小米", industry:"硬件+互联网", tags:["全国多地"], url:"https://hr.xiaomi.com/campus", desc:"手机+汽车+IoT全链", deadline:"2026-09-15", source:"官网", referral:""},
  {name:"网易", industry:"互联网", tags:["游戏+音乐+教育"], url:"https://campus.163.com/", desc:"多业务线同步招聘", deadline:"2026-09-20", source:"官网", referral:""},
  {name:"拼多多", industry:"电商", tags:["上海","增长快"], url:"https://careers.pinduoduo.com/", desc:"电商新贵，运营+供应链", deadline:"2026-09-30", source:"官网", referral:""},
  {name:"蔚来", industry:"新能源", tags:["汽车+智能化"], url:"https://campus.nio.com/", desc:"新能源车企，岗位多元", deadline:"2026-10-15", source:"官网", referral:""},
  {name:"Shopee", industry:"电商", tags:["深圳","东南亚"], url:"https://app.mokahr.com/campus_apply/shopee/2962/", desc:"跨境电商赛道", deadline:"2026-09-30", source:"官网", referral:""},
  {name:"米哈游", industry:"游戏", tags:["上海/深圳"], url:"https://campus.mihoyo.com/", desc:"游戏行业顶流", deadline:"2026-09-15", source:"官网", referral:""},
  {name:"哔哩哔哩", industry:"互联网", tags:["北上渝"], url:"https://jobs.bilibili.com/", desc:"Z世代社区", deadline:"2026-09-30", source:"官网", referral:""},
  {name:"vivo", industry:"硬件", tags:["多地"], url:"https://hr.vivo.com/", desc:"手机+IoT", deadline:"2026-09-30", source:"官网", referral:""},
  {name:"OPPO", industry:"硬件", tags:["10城"], url:"https://career.oppo.com/", desc:"手机+芯片+IoT", deadline:"2026-09-30", source:"官网", referral:""},
  {name:"英特尔", industry:"半导体", tags:["京沪蓉"], url:"https://jobs.intel.com/", desc:"芯片巨头", deadline:"2026-10-31", source:"官网", referral:""},
  {name:"宝洁", industry:"快消", tags:["管培生","8-9月"], url:"https://careers.pg.com.cn/", desc:"快消巨头，零售管理对口", deadline:"2026-09-20", source:"官网", referral:""},
  {name:"联合利华", industry:"快消", tags:["管培生","9月"], url:"https://www.unilever.com.cn/careers/", desc:"快消管培，供应链+市场", deadline:"2026-10-15", source:"官网", referral:""},
  {name:"欧莱雅", industry:"快消", tags:["管培生"], url:"https://careers.loreal.com/", desc:"美妆快消，品牌管理方向", deadline:"2026-10-15", source:"官网", referral:""},
  {name:"可口可乐", industry:"快消", tags:["管培生","上海"], url:"https://www.coca-colacompany.com/careers", desc:"饮料巨头，上海总部", deadline:"2026-10-31", source:"官网", referral:""},
  {name:"百胜中国", industry:"餐饮零售", tags:["管培生"], url:"https://careers.yumchina.com/", desc:"餐饮零售龙头，门店管理", deadline:"2026-10-31", source:"官网", referral:""},
  {name:"沃尔玛", industry:"零售", tags:["管培生","山姆"], url:"https://careers.walmart.cn/", desc:"全球零售第一", deadline:"2026-10-31", source:"官网", referral:""},
  {name:"华润万家", industry:"零售", tags:["国企","全国"], url:"https://crc.wintalent.cn/", desc:"央企零售，稳定有保障", deadline:"2026-10-31", source:"官网", referral:""},
  {name:"知乎", industry:"互联网", tags:["北京"], url:"https://app.mokahr.com/campus_apply/zhihu/3818/", desc:"内容平台校招", deadline:"2026-09-30", source:"官网", referral:""},
];
